version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build_and_test

jobs:
  build_and_test:
    working_directory: ~/ContactsManager
    docker:
      # Primary container: Ruby (with browsers for system tests)
      - image: cimg/ruby:3.1-browsers
        environment:
          RAILS_ENV: test
      # Secondary container: PostgreSQL
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Hamada1985@
          POSTGRES_DB: contacts_manager_test
    steps:
      - checkout

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate

      - run:
          name: Run Tests
          command: bundle exec rails test

  deploy:
    working_directory: ~/ContactsManager
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: ssh -o StrictHostKeyChecking=no $EC2_Connect@$EC2_PUBLIC_DNS rm -rf ContactsManager/; git clone https://github.com/MuhannedG/ContactsManager.git; source ContactsManager/deploy.sh