version: 2.1

workflows:
  build_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test

jobs:
  build_and_test:
    docker:
      # Primary container: Ruby + browsers for system tests
      - image: cimg/ruby:3.1-browsers
        environment:
          RAILS_ENV: test
      # Secondary container: PostgreSQL
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: my_app_test
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:migrate
      - run:
          name: Run Tests
          command: bundle exec rails test
