# config/database.yml

default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: Hamada1985@
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: contacts_manager_development

test:
  <<: *default
  database: contacts_manager_test

production:
  <<: *default
  database: contacts_manager_production
  username: <%= ENV['CONTACTS_MANAGER_DATABASE_USER'] %>
  password: <%= ENV['CONTACTS_MANAGER_DATABASE_PASSWORD'] %>
